[[redirects]]
from = "/api/*"
to = "/.netlify/functions/index"
status = 200
force = true

[functions]
directory = "netlify/functions"
command = "pnpm build & cp -r netlify/functions dist/netlify/functions"
publish = "dist"
